In [77]:
import pandas as pd
import datetime

In [78]:
df_taxi_zone_lk = pd.read_csv('./taxi_zone_lookup.csv')

In [79]:
df_taxi_zone_lk.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [80]:
df_greentrip = pd.read_parquet('./green_tripdata_2025-11.parquet')

In [81]:
# Question 3
date_upper = datetime.date(2025, 12, 1)
date_lower = datetime.date(2025, 11, 1)

cnt_short_trip_df = df_greentrip.loc[
    (df_greentrip['trip_distance'] <= 1) 
    & (df_greentrip['lpep_pickup_datetime'] >= pd.Timestamp(date_lower)) 
    & (df_greentrip['lpep_pickup_datetime'] < pd.Timestamp(date_upper))
]
len(cnt_short_trip_df)
# 8007

8007

In [82]:
# Question 4
longest_trip_distance = df_greentrip.loc[
    (df_greentrip['trip_distance'] < 100) 
    & (df_greentrip['trip_distance'] == max(longest_trip_distance['trip_distance']))
]
longest_trip_distance['lpep_pickup_datetime']
# 2025-11-14 15:36:27

18867   2025-11-14 15:36:27
Name: lpep_pickup_datetime, dtype: datetime64[us]

In [83]:
# Question 5
pickup_date = datetime.date(2025, 11, 18)

biggest_pickup = df_greentrip.loc[
    df_greentrip['lpep_pickup_datetime'].dt.date == pickup_date
]

top1 = (biggest_pickup.groupby("PULocationID", as_index=False)["total_amount"]
          .sum()
          .sort_values("total_amount", ascending=False)
          .head(1))

location_id = top1['PULocationID'].values[0]

biggest_pickup_zone = df_taxi_zone_lk.loc[
    df_taxi_zone_lk['LocationID'] == location_id
]

biggest_pickup_zone
# 74	Manhattan	East Harlem North	Boro Zone

    LocationID    Borough               Zone service_zone
73          74  Manhattan  East Harlem North    Boro Zone

In [84]:
# Question 6
date_upper = datetime.date(2025, 11, 30)
date_lower = datetime.date(2025, 11, 1)

location_df = df_taxi_zone_lk.loc[
    df_taxi_zone_lk['Zone'] == 'East Harlem North'
]

location_id = location_df['LocationID'].values[0]

tip_df = df_greentrip.loc[
    (df_greentrip['PULocationID'] == location_id) 
    & (df_greentrip['lpep_pickup_datetime'] >= pd.Timestamp(date_lower)) 
    & (df_greentrip['lpep_pickup_datetime'] <= pd.Timestamp(date_upper))
]

largest_tip = tip_df.loc[
    (tip_df['tip_amount'] == max(tip_df['tip_amount'])) 
]
do_location_id = largest_tip['DOLocationID'].values[0]

largest_tip_dropoff_zone = df_taxi_zone_lk.loc[
    df_taxi_zone_lk['LocationID'] == do_location_id
]

largest_tip_dropoff_zone
# 138	Queens	LaGuardia Airport	Airports

     LocationID Borough               Zone service_zone
137         138  Queens  LaGuardia Airport     Airports